gaps outer 4
gaps inner 10
default_border pixel 2

client.focused          #afafaf #afafaf #afafaf #afafaf #afafaf
client.unfocused        #676700 #676700 #676700 #676700 #676700
client.focused_inactive #dddddd #dddddd #000000 #dddddd #dddddd
client.urgent           #ffcccc #ffcccc #000000 #ffcccc #ffcccc