gaps outer 4
gaps inner 10
default_border pixel 2

client.focused          #ffffff #ffffff #000000 #ffffff #ffffff
client.unfocused        #002f01 #002f01 #002f01 #002f01 #002f01
client.focused_inactive #dddddd #dddddd #000000 #dddddd #dddddd
client.urgent           #ffcccc #ffcccc #000000 #ffcccc #ffcccc